### ISSUE TITLE
Scanning stops at 2897 subdomains...

### ISSUE THREAD

**Issue by demajkel** [m0rtem/CloudFail#10] opened 2017-06-27 00:49 UTC
as above, when I run cloudfail.py the whole process stops on subdomains scans!

I waited over 2 hours for the results but he was there! 'please wait...' he's still there!!! :)

**Comment by Elycin** [comment] 2017-06-29 15:55
This is not a bug. 
A quick look at the subdomains file in the data folder shows there is exactly 2897 subdomains the script scans for.

**Comment by demajkel** [comment] 2017-06-30 07:22
@Elycin thanks for that answer but i already knew that before ;) 
I understand that the script needs so much time to complete the scan?

**Comment by m0rtem** [comment] 2017-07-04 10:13
There is an indication as to when the scan has finished, progress bars are a feature which I am currently working on and will be included in a later version.

**Comment by m0rtem** [comment] 2017-07-05 08:15
This has now been included as of commit 325ccbd4a880f5f4d1c39f07b167aabdbecad4c9 thanks too: @bdoner

**Closed** 2017-07-05 08:15 UTC

**Comment by demajkel** [comment] 2017-07-05 10:48
hi! Thx for re. and progress bar ;) 
If somebody have similar problem with long time scanning, try to upgrade your distribution!
In my case that helped! ;)
